// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
//   eclSidebar: [
//     {
//       type: 'category',
//       label: 'Fiches HOLIS',
//       collapsed: false,
//       items: [
//         'intro',
//         'summary'
//       ],
//     },
//   ],
//   eclSidebar: [
//     {
//       type: 'category',
//       label: 'Fiches HOLIS',
//       collapsed: false,
//       items: [
//         'intro',
//         'summary'
//       ],
//     },
//   ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 crewSidebar: [{type: 'autogenerated', dirName: 'crew'}],
 eclSidebar: [{type: 'autogenerated', dirName: 'ecl'}],
 gocSidebar: [{type: 'autogenerated', dirName: 'goc'}],
 mccSidebar: [{type: 'autogenerated', dirName: 'mcc'}],
 occSidebar: [{type: 'autogenerated', dirName: 'occ'}],
 opsSidebar: [{type: 'autogenerated', dirName: 'ops'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
